# Generated by Django 2.2.10 on 2021-05-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=200)),
                ('a_digits', models.IntegerField(default=2)),
                ('b_digits', models.IntegerField(default=2)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('user_answer', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('correct', models.BooleanField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.FloatField(blank=True, default=None, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date')),
            ],
            options={
                'get_latest_by': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=200)),
                ('a_digits', models.IntegerField()),
                ('b_digits', models.IntegerField()),
                ('daily_target', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
