# Generated by Django 2.2.10 on 2021-12-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='read_aloud',
            field=models.BooleanField(default=False),
        ),
    ]
