# Generated by Django 2.2.10 on 2021-12-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_question_read_aloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='show_question',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='speech_recognition',
            field=models.BooleanField(default=False),
        ),
    ]
